version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      #HIDDEN_NEURONS: ${HIDDEN_NEURONS:-16}
      #LIMIT_PER_DIGIT: ${LIMIT_PER_DIGIT:-17}
      #NUM_CLASSES: ${NUM_CLASSES:-10}
      HIDDEN_NEURONS: 8
      LIMIT_PER_DIGIT: 16
      NUM_CLASSES: 10
